version: "2"
linters:
  enable:
    - nlreturn
    - revive
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: strict
    paths:
      - third_party$
      - builtin$
      - examples$
