services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env


    environment:
      NS_MARIADB_USER: root
      NS_MARIADB_PASSWORD: pass
      NS_MARIADB_HOSTNAME: db
      NS_MARIADB_PORT: "3306"
      NS_MARIADB_DATABASE: app
      JWT_SECRET: "your_super_secure_jwt_secret_key_32_chars_minimum_length_required"

  
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  db:
    image: mariadb:10.11
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: app
    expose:
      - "3306"
    healthcheck:
      test: mysql --user=root --password=pass --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 30

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
